"""Canonical physical names below a VibeSys project root."""

from pathlib import Path, PurePosixPath

CONFIGURATION_DIRECTORY_NAME = ".vibesys"
TASKS_DIRECTORY_NAME = "tasks"
STATE_DIRECTORY_NAME = "state"
EVALUATOR_LOCK_FILE_NAME = "evaluators.lock"
OBJECTIVE_FILE_NAME = "OBJECTIVE.md"
MANIFEST_FILE_NAME = "vibesys.input.toml"

STATE_DIRECTORY_PARTS = (CONFIGURATION_DIRECTORY_NAME, STATE_DIRECTORY_NAME)
STATE_DIRECTORY_PATH = Path(*STATE_DIRECTORY_PARTS)
STATE_DIRECTORY_POSIX = PurePosixPath(*STATE_DIRECTORY_PARTS)
